# Generated by Django 2.2.28 on 2026-03-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_society'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='society_images'),
        ),
    ]
