# Generated by Django 2.2.28 on 2026-03-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0007_auto_20260313_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='society',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
