# Generated by Django 2.2.28 on 2026-03-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0007_auto_20260311_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='society',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
