# Generated by Django 2.2.28 on 2026-03-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_auto_20260313_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='society',
            name='category',
        ),
        migrations.AddField(
            model_name='society',
            name='categories',
            field=models.ManyToManyField(to='rango.Category'),
        ),
    ]
