# Generated by Django 2.2.28 on 2026-03-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_auto_20260311_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
